import { createClientFromRequest } from 'npm:@base44/sdk@0.8.31';

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();
    if (!user) return Response.json({ error: 'Unauthorized' }, { status: 401 });

    const now = new Date();
    const yesterday = new Date(now.getTime() - 24 * 3600 * 1000).toISOString();

    // Fetch audit logs from last 24 hours
    const auditLogs = await base44.asServiceRole.entities.AuditLog.filter(
      { created_date: { $gte: yesterday } },
      "-created_date",
      500
    );

    // Fetch unresolved audit flags
    const unresolvedFlags = await base44.asServiceRole.entities.AuditFlag.filter(
      { is_resolved: false },
      "-created_date",
      100
    );

    // Aggregate by entity type
    const byEntity = {};
    const byAction = {};
    auditLogs.forEach(log => {
      byEntity[log.entity_type] = (byEntity[log.entity_type] || 0) + 1;
      byAction[log.action] = (byAction[log.action] || 0) + 1;
    });

    // Build summary
    const entityBreakdown = Object.entries(byEntity)
      .map(([entity, count]) => `  • ${entity}: ${count} changes`)
      .join('\n');

    const actionBreakdown = Object.entries(byAction)
      .map(([action, count]) => `  • ${action}: ${count}`)
      .join('\n');

    const flagSummary = unresolvedFlags.length > 0
      ? `⚠️ UNRESOLVED AUDIT FLAGS: ${unresolvedFlags.length}\n` +
        unresolvedFlags.slice(0, 5).map(f =>
          `  • ${f.discrepancy_type} — Diff: MWK ${f.difference?.toLocaleString()} (${f.severity})`
        ).join('\n')
      : '✅ No unresolved audit flags.';

    const body = `DAILY AUDIT REPORT — ${now.toLocaleDateString('en-GB', { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' })}

━━━━━━━━━━━━━━━━━━━━━━━━
SUMMARY
━━━━━━━━━━━━━━━━━━━━━━━━
Total audit events (24h): ${auditLogs.length}
Unresolved flags: ${unresolvedFlags.length}

━━━━━━━━━━━━━━━━━━━━━━━━
BY ENTITY TYPE
━━━━━━━━━━━━━━━━━━━━━━━━
${entityBreakdown || '  (none)'}

━━━━━━━━━━━━━━━━━━━━━━━━
BY ACTION
━━━━━━━━━━━━━━━━━━━━━━━━
${actionBreakdown || '  (none)'}

━━━━━━━━━━━━━━━━━━━━━━━━
FLAGS
━━━━━━━━━━━━━━━━━━━━━━━━
${flagSummary}

━━━━━━━━━━━━━━━━━━━━━━━━
Generated by Zomba City Private Clinic HIMS
━━━━━━━━━━━━━━━━━━━━━━━━`;

    // Send email to all admin users
    const allUsers = await base44.asServiceRole.entities.User.list("", 50);
    const admins = allUsers.filter(u => u.role === 'admin' && u.email);

    for (const admin of admins.slice(0, 5)) {
      try {
        await base44.asServiceRole.integrations.Core.SendEmail({
          to: admin.email,
          subject: `Daily Audit Alert — ${now.toLocaleDateString('en-GB')}`,
          body: body,
          from_name: 'Zomba Clinic Audit',
        });
      } catch (_) { /* skip failed sends */ }
    }

    return Response.json({
      success: true,
      total_events: auditLogs.length,
      unresolved_flags: unresolvedFlags.length,
      entity_breakdown: byEntity,
      action_breakdown: byAction,
      admins_notified: admins.length,
    });
  } catch (error) {
    return Response.json({ error: error.message }, { status: 500 });
  }
});