import { createClientFromRequest } from 'npm:@base44/sdk@0.8.31';

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();
    if (!user) return Response.json({ error: 'Unauthorized' }, { status: 401 });

    const now = new Date();
    const dateStr = now.toISOString().slice(0, 10);
    const timeStr = now.toLocaleString('en-GB', {
      day: '2-digit', month: 'short', year: 'numeric',
      hour: '2-digit', minute: '2-digit',
    });

    // --- PHARMACY ---
    const activeDrugs = await base44.asServiceRole.entities.Drug.filter(
      { status: 'active' }, '', 500
    );
    const lowDrugs = activeDrugs.filter(d => d.quantity_in_stock <= d.reorder_level);

    // --- LABORATORY ---
    const activeReagents = await base44.asServiceRole.entities.LabReagent.filter(
      { status: 'active' }, '', 500
    );
    const lowReagents = activeReagents.filter(r => r.quantity_in_stock <= r.reorder_level);

    const totalItems = lowDrugs.length + lowReagents.length;

    if (totalItems === 0) {
      return Response.json({
        success: true,
        items_found: 0,
        message: 'No low-stock items found today.',
      });
    }

    // Build CSV string
    const headers = 'Item Name,Category,Current Stock,Reorder Level,Suggested Qty,Unit,Unit Price (MWK),Est. Cost (MWK),Status,Expiry,Batch/Lot,Storage';
    const drugRows = lowDrugs.map(d => {
      const qty = Math.max(d.reorder_level * 3, (d.safety_stock_days || 30) + d.reorder_level * 2);
      const price = d.cost_price || d.unit_price || 0;
      return `"${d.name}",Pharmacy Drug,${d.quantity_in_stock},${d.reorder_level},${qty},${d.form || '—'},${price},${Math.round(qty * price)},${d.quantity_in_stock === 0 ? 'OUT OF STOCK' : 'Low Stock'},${d.expiry_date || '—'},${d.batch_number || '—'},${d.requires_refrigeration ? 'Refrigerated' : 'Room Temp'}`;
    });
    const labRows = lowReagents.map(r => {
      const qty = Math.max(r.reorder_level * 3, 15);
      const storage = r.requires_cold_chain ? `${r.storage_condition || 'Refrigerated'} (Cold Chain)` : (r.storage_condition || 'Room Temp');
      return `"${r.name}",Lab Reagent,${r.quantity_in_stock},${r.reorder_level},${qty},${r.unit || 'unit'},—,—,${r.quantity_in_stock === 0 ? 'OUT OF STOCK' : 'Low Stock'},${r.expiry_date || '—'},${r.lot_number || '—'},${storage}`;
    });

    const csvContent = [headers, ...drugRows, ...labRows].join('\n');

    // Build email
    const subject = `[HIMS] Daily Reorder Report — ${dateStr} (${totalItems} items)`;

    const bodyText = [
      `Zomba City Private Clinic — Daily Low-Stock Reorder Report`,
      `══════════════════════════════════════════════════`,
      ``,
      `Generated: ${timeStr}`,
      `Total items needing reorder: ${totalItems}`,
      `  • Pharmacy Drugs: ${lowDrugs.length} (${lowDrugs.filter(d => d.quantity_in_stock === 0).length} out of stock)`,
      `  • Lab Reagents: ${lowReagents.length} (${lowReagents.filter(r => r.quantity_in_stock === 0).length} out of stock)`,
      ``,
      `──────────────────────────────────────────────────`,
      `COPY THE LINES BELOW INTO GOOGLE SHEETS:`,
      `  1. Select and copy all lines starting from "Item Name" below`,
      `  2. Open sheets.google.com → Blank spreadsheet`,
      `  3. Click cell A1 → Paste (Ctrl+V / Cmd+V)`,
      `  4. Data → Split text to columns → Separator: Comma`,
      `──────────────────────────────────────────────────`,
      ``,
      csvContent,
      ``,
      `──────────────────────────────────────────────────`,
      `End of report. Generated by Zomba City HIMS.`,
    ].join('\n');

    // Email to all admin users
    const adminUsers = await base44.asServiceRole.entities.User.filter({ role: 'admin' }, '', 50);
    const emailResults = [];

    for (const admin of adminUsers) {
      if (!admin.email) continue;
      try {
        await base44.asServiceRole.integrations.Core.SendEmail({
          to: admin.email,
          subject,
          body: bodyText,
          from_name: 'Zomba City HIMS — Reorder',
        });
        emailResults.push({ email: admin.email, sent: true });
      } catch (e) {
        emailResults.push({ email: admin.email, sent: false, error: e.message });
      }
    }

    // Create in-app notification
    await base44.asServiceRole.entities.Notification.create({
      title: `📊 Daily Reorder Report — ${totalItems} Items`,
      message: `Low-stock report for ${dateStr}: ${lowDrugs.length} pharmacy + ${lowReagents.length} lab items. Emailed to ${emailResults.filter(r => r.sent).length} admin(s) with CSV data ready for Google Sheets import.`,
      type: 'info',
      target_role: 'admin',
      action_url: '/pharmacy',
    });

    return Response.json({
      success: true,
      generated_at: now.toISOString(),
      items_found: totalItems,
      pharmacy_items: lowDrugs.length,
      lab_items: lowReagents.length,
      emails_sent: emailResults.filter(r => r.sent).length,
      email_results: emailResults,
    });
  } catch (error) {
    return Response.json({ error: error.message }, { status: 500 });
  }
});